### ISSUE TITLE
修改由晖子能力文档

### ISSUE THREAD

**Issue by rolevax** [mjpancake/mjpancake.github.io#2]
具体要求如下：

- 以下关键点必须提及
    - 每天一次
    - 神之力
- 提及关键点时，尽可能照搬生肉原文
- 除以上两个关键点外，不要添加能力细节
    - 参考现有的鸭子能力文档，越暧昧越好
- 措词不要太功利，不要以竞技玩家的角度露骨地描述机能
    - 需要带有一定的感情与文艺成分
- 笔风与现有其它角色能力文档保持一致
- 总行数不得超过5行，3行以内更好
- 单行不得超过30个字

提交方式：（二选一）

1. 直接在本issue下方回复
2. QQ 1493690468

提交内容：

- 修改后的由晖子的文档正文

验收通过条件：

- 符合上面提及的所有要求

遇到任何问题，可通过Gitter或QQ提问，或直接在本issue下回复

**Comment by TheTSD** [comment]
·每天一次，在开局前或对局中，询问对手征得同意后切换左手摸切，仅在该局中发动神之力。
-发动期间，进章的速度与火力都显著提升。
-因为是神之力，难以用凡人的操作来阻止她的和牌。
-立直和牌后高几率开出里宝牌。

**Comment by rolevax** [comment]
其实离要求有一定距离

1. 第一行太长
2. “速度与火力显著提升”是关键点以外的能力细节，都说了不要加了
3. “因为是神之力，所以没法阻挡”原作没有明确交代这种因果关系
4. “里宝牌”也是关键点以外的细节

下面就一个能满足所有要求的例子：

- 每天可向对手申请一次使用左手
- 使用左手后可以神之力闪blind她们的dog eyes
