### ISSUE TITLE
增加绢惠的能力文档

### ISSUE THREAD

**Issue by rolevax** [mjpancake/mjpancake.github.io#3]
具体要求如下：

- 简单照搬181原话
- 不要添加未经证实的能力细节
- 措词不要太功利，不要以竞技玩家的角度露骨地描述机能
    - 需要带有一定的感情与文艺成分
- 笔风与现有其它角色能力文档保持一致
- 总行数不得超过5行，3行以内更好
- 单行不得超过40个字

提交方式：（二选一）

1. 直接在本issue下方回复
2. QQ 1493690468

提交内容：

- 新写的绢惠文档正文

验收通过条件：

- 符合上面提及的所有要求

遇到任何问题，可通过Gitter或QQ提问，或直接在本issue下回复

**Comment by I-sakisan** [comment]
(*)足球妹
·因为踢过足球，所以和圆形的东西有缘
        容易以筒子和好牌
        踢飞可疑的圆形物体，能缓解压♀力
